# Site wide configuration

title: 三石的个人网站
locale: en_US
description: 但行好事，莫问前程
logo: site-logo.png

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname



# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..5
  use_coderay: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:

  name: goaheadalvin
  avatar: leifu.jpg
  email: goaheadalvin@gmail.com
  disqus-shortname: goaheadalvin
  duoshuo: goaheadalvin
  config: true
  id: leifu
  twitter: goaheadalvin
  facebook: profile.php?id=100004326459944
#  github: goaheadalvin
  stackexchange:
  linkedin: lei-alvin-fu/39/675/3ba/
  instagram: sangeshitou
  flickr:
  tumblr: 
  google:
    plus: 107282615831289677152/about
    analytics: UA-59023785-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify:
  weixin: weixin
  weibo: mynameisalvin


      
    